# Generated by Django 4.1.1 on 2022-11-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("address", models.TextField()),
                ("phone", models.IntegerField()),
            ],
        ),
    ]
